<?php

declare(strict_types=1);

namespace CmsOrbit\Core\Commands;

use CmsOrbit\Core\Support\Facades\OrbitPackage;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

/**
 * Generate Vite Config Command
 *
 * OrbitPackage에 등록된 자원을 JS 파일로 출력
 * IDE와 Vite에서 사용 가능하도록 resources/js/lib/ 에 생성
 */
class GenerateViteConfigCommand extends Command
{
    /**
     * The name and signature of the console command
     *
     * @var string
     */
    protected $signature = 'cms:build-config';

    /**
     * The console command description
     *
     * @var string
     */
    protected $description = 'Build Orbit configuration files for Vite and Tailwind';

    /**
     * Execute the console command
     */
    public function handle(): int
    {
        $this->info('Building Orbit configuration...');

        // Use absolute path from package root (core directory)
        $packageRoot = dirname(dirname(dirname(dirname(__FILE__))));
        $libPath = $packageRoot.'/resources/js/lib';

        if (! is_dir($libPath)) {
            if (! mkdir($libPath, 0755, true)) {
                $this->error("Failed to create directory: {$libPath}");

                return self::FAILURE;
            }
        }

        // Generate vite.js
        $this->generateViteConfig($libPath);

        // Generate tailwind.js
        $this->generateTailwindConfig($libPath);

        // Generate alias.js (for IDE)
        $this->generateAliasConfig($libPath);

        $this->newLine();
        $this->info('✓ Configuration files generated!');
        $this->newLine();
        $this->comment('Files created:');
        $this->line('  packages/cms-orbit/core/resources/js/lib/vite.js');
        $this->line('  packages/cms-orbit/core/resources/js/lib/tailwind.js');
        $this->line('  packages/cms-orbit/core/resources/js/lib/alias.js');
        $this->newLine();
        $this->comment('Update your vite.config.js:');
        $this->newLine();
        $this->line("import { viteConfig } from '@cms-orbit/core/lib/vite';");
        $this->line('');
        $this->line('export default defineConfig({');
        $this->line('    ...viteConfig,');
        $this->line('    plugins: [');
        $this->line('        laravel({');
        $this->line('            input: [\'resources/js/app.tsx\', ...viteConfig.input],');
        $this->line('        }),');
        $this->line('    ],');
        $this->line('});');
        $this->newLine();
        $this->comment('Update your tailwind.config.js:');
        $this->newLine();
        $this->line("import { tailwindConfig } from '@cms-orbit/core/lib/tailwind';");
        $this->line('');
        $this->line('export default {');
        $this->line('    content: [');
        $this->line('        \'./resources/**/*.tsx\',');
        $this->line('        ...tailwindConfig.content,');
        $this->line('    ],');
        $this->line('};');

        return self::SUCCESS;
    }

    /**
     * Generate vite.js
     */
    protected function generateViteConfig(string $libPath): void
    {
        $aliases = $this->prepareAliases();
        $inputs = OrbitPackage::getViteEntries();

        $content = "// Auto-generated by cms:build-config\n";
        $content .= "// Do not edit manually\n\n";
        $content .= "export const viteConfig = {\n";
        $content .= "    resolve: {\n";
        $content .= '        alias: '.$this->formatJs($aliases).",\n";
        $content .= "    },\n";
        $content .= '    input: '.json_encode($inputs, JSON_UNESCAPED_SLASHES).",\n";
        $content .= "};\n";

        $result = file_put_contents($libPath.'/vite.js', $content);

        if ($result === false) {
            $this->error("Failed to write {$libPath}/vite.js");
        }
    }

    /**
     * Generate tailwind.js
     */
    protected function generateTailwindConfig(string $libPath): void
    {
        $contents = OrbitPackage::getTailwindContents();

        $content = "// Auto-generated by cms:build-config\n";
        $content .= "// Do not edit manually\n\n";
        $content .= "export const tailwindConfig = {\n";
        $content .= '    content: '.json_encode($contents, JSON_UNESCAPED_SLASHES).",\n";
        $content .= "};\n";

        $result = file_put_contents($libPath.'/tailwind.js', $content);

        if ($result === false) {
            $this->error("Failed to write {$libPath}/tailwind.js");
        }
    }

    /**
     * Generate alias.js (for IDE)
     */
    protected function generateAliasConfig(string $libPath): void
    {
        $aliases = $this->prepareAliases();

        $content = "// Auto-generated by cms:build-config\n";
        $content .= "// For IDE path intellisense\n\n";
        $content .= 'export default '.$this->formatJs($aliases).";\n";

        $result = file_put_contents($libPath.'/alias.js', $content);

        if ($result === false) {
            $this->error("Failed to write {$libPath}/alias.js");
        }
    }

    /**
     * Format array as JS object
     */
    protected function formatJs(array $data): string
    {
        if (empty($data)) {
            return '{}';
        }

        $lines = [];
        foreach ($data as $key => $value) {
            $lines[] = "        '{$key}': '{$value}'";
        }

        return "{\n".implode(",\n", $lines)."\n    }";
    }

    /**
     * Prepare aliases with absolute paths
     */
    protected function prepareAliases(): array
    {
        $paths = OrbitPackage::getPaths();
        $aliases = [];

        // Add default @ alias
        $aliases['@'] = './resources/js';

        foreach ($paths as $alias => $path) {
            // Convert absolute paths to relative from project root
            if (Str::startsWith($path, base_path())) {
                $path = './'.Str::after($path, base_path().'/');
            }

            $aliases[$alias] = $path;
        }

        return $aliases;
    }
}
