<?php

declare(strict_types=1);

namespace CmsOrbit\Core\Frontend;

use Illuminate\Support\Str;

final class FrontendSync
{
    private const VITE_MARKER_START = '// ORBIT:ALIASES:START';

    private const VITE_MARKER_END = '// ORBIT:ALIASES:END';

    public function __construct(private readonly string $basePath) {}

    /**
     * @return array{bridges: list<string>, vite: bool, aliases: list<string>}
     */
    public function sync(bool $force = false): array
    {
        $manifests = FrontendManifest::discover($this->basePath);
        $createdBridges = [];
        $aliases = [];

        foreach ($manifests as $manifest) {
            $aliases[] = $manifest->alias();

            foreach ($manifest->pages() as $page) {
                $bridgePath = $this->bridgePath($page['component']);

                if (! $force && is_file($bridgePath)) {
                    continue;
                }

                $this->writeBridge($bridgePath, $page, $manifest->alias());
                $createdBridges[] = $this->relativePath($bridgePath);
            }
        }

        $viteUpdated = $this->syncViteAliases($manifests);

        return [
            'bridges' => $createdBridges,
            'vite'    => $viteUpdated,
            'aliases' => $aliases,
        ];
    }

    /**
     * @param list<FrontendManifest> $manifests
     */
    private function syncViteAliases(array $manifests): bool
    {
        $vitePath = $this->resolveViteConfigPath();

        if ($vitePath === null) {
            return false;
        }

        $aliasBlock = $this->buildViteAliasBlock($manifests);
        $contents = (string) file_get_contents($vitePath);

        if (str_contains($contents, self::VITE_MARKER_START) && str_contains($contents, self::VITE_MARKER_END)) {
            $updated = (string) preg_replace(
                '/'.preg_quote(self::VITE_MARKER_START, '/').'.*?'.preg_quote(self::VITE_MARKER_END, '/').'/s',
                self::VITE_MARKER_START."\n".$aliasBlock.self::VITE_MARKER_END,
                $contents,
            );
        } elseif (preg_match('/alias\s*:\s*\{/', $contents) === 1) {
            $updated = preg_replace(
                '/(alias\s*:\s*\{)/',
                '$1'."\n".self::VITE_MARKER_START."\n".$aliasBlock.self::VITE_MARKER_END."\n",
                $contents,
                1,
            );
            $updated = is_string($updated) ? $updated : $contents;
        } else {
            return false;
        }

        if ($updated === $contents) {
            return false;
        }

        file_put_contents($vitePath, $updated);

        return true;
    }

    /**
     * @param list<FrontendManifest> $manifests
     */
    private function buildViteAliasBlock(array $manifests): string
    {
        $lines = [];

        foreach ($manifests as $manifest) {
            $relativeJsRoot = $this->relativePath($manifest->jsRoot());
            $lines[] = sprintf(
                "            '%s': fileURLToPath(new URL('./%s', import.meta.url)),",
                $manifest->alias(),
                str_replace(DIRECTORY_SEPARATOR, '/', $relativeJsRoot),
            );
        }

        if ($lines === []) {
            return '';
        }

        return implode("\n", $lines)."\n";
    }

    private function writeBridge(string $bridgePath, array $page, string $alias): void
    {
        $directory = dirname($bridgePath);

        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $component = $page['component'];
        $exportPath = $page['export'];

        $contents = <<<TSX
/**
 * Auto-generated by `php artisan orbit:frontend-sync`.
 * Host bridge for the Orbit "{$component}" page.
 */
export { default } from '{$alias}/{$exportPath}';

TSX;

        file_put_contents($bridgePath, $contents);
    }

    private function bridgePath(string $component): string
    {
        return $this->basePath
            .DIRECTORY_SEPARATOR.'resources'
            .DIRECTORY_SEPARATOR.'js'
            .DIRECTORY_SEPARATOR.'pages'
            .DIRECTORY_SEPARATOR.str_replace('/', DIRECTORY_SEPARATOR, $component).'.tsx';
    }

    private function resolveViteConfigPath(): ?string
    {
        foreach (['vite.config.ts', 'vite.config.js', 'vite.config.mjs'] as $filename) {
            $path = $this->basePath.DIRECTORY_SEPARATOR.$filename;

            if (is_file($path)) {
                return $path;
            }
        }

        return null;
    }

    private function relativePath(string $absolutePath): string
    {
        $normalizedBase = rtrim(str_replace('\\', '/', $this->basePath), '/').'/';
        $normalizedPath = str_replace('\\', '/', $absolutePath);

        return Str::startsWith($normalizedPath, $normalizedBase)
            ? Str::after($normalizedPath, $normalizedBase)
            : $normalizedPath;
    }
}
